<div class="contentvhr">
    <h1>News</h1><hr/>
    <p>&nbsp;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eu placerat magna, ac imperdiet ante. Curabitur eget quam mauris. Aliquam vitae luctus eros. Duis lorem eros, congue eu feugiat vel, bibendum quis enim. Nulla eu rhoncus lectus, vel tincidunt mauris. Maecenas ac diam scelerisque sem volutpat pretium. Donec sollicitudin mi et commodo molestie. Cras ultrices placerat erat, quis placerat erat. Mauris a erat at dui efficitur mattis vel sed mi. Sed eget nisl ac ante posuere sodales eu id arcu. Morbi tincidunt nunc et massa faucibus, id efficitur lacus hendrerit. Pellentesque tincidunt sit amet ipsum eu laoreet. Morbi aliquam faucibus lacus, nec placerat dolor ultricies ac.</p><p>
    <p>&nbsp;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tempor, erat lobortis porta ornare, augue felis consequat orci, ac posuere turpis ex id erat. Fusce id porta sapien. Nullam ac finibus orci. Pellentesque in nulla non justo pulvinar tristique id nec erat. Integer faucibus lacus in mi consectetur lobortis. Mauris id nisl eu dolor congue fringilla. Aliquam blandit id mauris nec semper. Nulla ut lobortis diam. Vestibulum non dui ut mi pellentesque vestibulum quis eget velit. Aliquam eget diam purus. Proin nulla metus, mollis quis blandit sed, pharetra ac magna. Pellentesque nec tincidunt risus. Vivamus nibh leo, ultrices ac faucibus eget, ultricies ut orci.</p><p>
    <p>&nbsp;Integer consequat quam nulla, quis tincidunt lorem rhoncus sit amet. Cras vitae nulla erat. Proin vehicula nisl auctor luctus tempus. Sed ut augue id nisi volutpat ultricies. Proin fringilla neque ante, nec molestie mi semper rhoncus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris rutrum urna posuere purus porttitor, eget faucibus dui vestibulum. Duis dapibus, velit ut imperdiet sodales, massa nisl elementum lorem, placerat gravida sem eros at orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p><p>
    <p>&nbsp;Donec id erat eget justo posuere cursus vitae sed orci. Curabitur commodo urna non risus sodales dapibus. Quisque et mauris vel tortor efficitur ultrices. Praesent commodo velit ut felis tristique, non aliquet urna lobortis. Fusce accumsan ullamcorper accumsan. Mauris ligula eros, mattis nec sollicitudin a, hendrerit ac ante. Donec volutpat purus ex, in scelerisque ipsum placerat pellentesque. Maecenas varius est nec ante iaculis, at cursus arcu aliquam. Praesent id viverra eros, eget malesuada ligula.</p><p>
    <p>&nbsp;Aenean vehicula tortor quis dapibus placerat. Vestibulum rhoncus, enim vel tincidunt condimentum, lorem dolor ornare massa, non tempus nisi nibh id purus. Aliquam semper ante vel ex tincidunt, sit amet gravida ante faucibus. Ut et libero in purus laoreet sodales. Nullam pretium eros nec urna malesuada, nec cursus purus imperdiet. Morbi faucibus sit amet nulla eu ornare. Etiam maximus, est eu suscipit venenatis, felis ante sodales ex, at hendrerit tortor metus id ex. Quisque dignissim lacus ornare nisl condi mentum gravida eu non nibh. Vestibulum aliquam, mauris vel accumsan porta, felis sapien gravida felis, sed interdum orci purus sit amet tortor. Quisque imperdiet arcu a consequat convallis. Curabitur a sapien id ante fringilla hendrerit.</p><p>
    <div class="news-link-container">
        <a href="#" class="news-link left"><i class="fa fa-caret-left" aria-hidden="true"></i>&nbsp;Previous</a>
        <a href="#" class="news-link right">Next&nbsp;<i class="fa fa-caret-right" aria-hidden="true"></i></a>
    </div>
</div>